services:
  frontend:

    build: ./frontend/frontend
    ports:
      - "3000:3000"
    networks:
      - network1
    environment:
      - TARGET_URL=http://backend:3001/add

  backend:
    build: ./backend
    ports:
      - "3001:80"
    networks:
      - network1

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
  
networks:
  network1:
    name: network1